# Site settings
title: "Miro Furtado"
email: furtadomiro@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: "mirofurtado.com"
url: "mirofurtado.com"
title_description: "Applied Math <b>@Harvard</b> </br> I have a passion for building costless abstractions for doing fast inference."
title_image: "/assets/MiroAtlas.png"
post_limit: 5

# Social usernames/URLs
twitter_username: MiroFurtado
github_username:  MiroFurtado
instagram_username: 
reddit_username: themiro
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
